// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eybgccaymptqyugzeuxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5YmdjY2F5bXB0cXl1Z3pldXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzExNDQsImV4cCI6MjA2NTQ0NzE0NH0.pDW3ZVbnWT9N_iZjFZISO4aPZiQAWpU5OTW8LGZ2Dfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);